import os
import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter()

CODA_API_BASE = "https://coda.io/apis/v1"


class CommitRequest(BaseModel):
    doc_id: str
    report: dict       # Extraction report from /extract
    diffs: list        # Approved diffs from /preview
    request_id: str    # Unique ID for this import job (generated by UI)
    uploaded_by: str = "importer"


def coda_headers():
    token = os.environ.get("CODA_API_TOKEN")
    if not token:
        raise HTTPException(status_code=500, detail="CODA_API_TOKEN not configured")
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }


async def upsert_row(client, doc_id, grid_id, cells, headers):
    """Create a single row in a Coda table."""
    payload = {"rows": [{"cells": cells}]}
    resp = await client.post(
        f"{CODA_API_BASE}/docs/{doc_id}/tables/{grid_id}/rows",
        json=payload,
        headers=headers,
    )
    if not resp.is_success:
        raise HTTPException(
            status_code=502,
            detail=f"Coda write failed [{grid_id}]: {resp.status_code} {resp.text[:200]}",
        )
    return resp.json()


async def update_row(client, doc_id, grid_id, row_id, cells, headers):
    """Update an existing row in a Coda table."""
    payload = {"row": {"cells": cells}}
    resp = await client.put(
        f"{CODA_API_BASE}/docs/{doc_id}/tables/{grid_id}/rows/{row_id}",
        json=payload,
        headers=headers,
    )
    if not resp.is_success:
        raise HTTPException(
            status_code=502,
            detail=f"Coda update failed [{grid_id}/{row_id}]: {resp.status_code} {resp.text[:200]}",
        )
    return resp.json()


@router.post("")
async def commit(req: CommitRequest):
    """
    Execute the approved CCW write sequence against Coda REST API.
    Steps follow the CCW import skill cascade order (Steps 1-9).
    Metadata columns written on every touched row.
    """
    report = req.report
    doc_id = req.doc_id
    headers = coda_headers()
    log = []
    written = 0

    course_level = report.get("course_level", {})
    competencies = report.get("competencies", [])
    context = report.get("context", {})
    course_row_id = context.get("course_row_id")
    program_row_id = context.get("program_row_id")

    metadata_cells = [
        {"column": "c-parsedByAI",    "value": True},
        {"column": "c-importStatus",   "value": "Imported"},
        {"column": "c-importedAt",     "value": context.get("imported_at", "")},
        {"column": "c-sourceFile",     "value": context.get("source_filename", "")},
        {"column": "c-uploadedBy",     "value": req.uploaded_by},
        {"column": "c-requestId",      "value": req.request_id},
    ]

    async with httpx.AsyncClient(timeout=30.0) as client:

        # ── Step 1-2: Course row ─────────────────────────────────────────────
        course_cells = [
            {"column": "c-sgyJdn2bVc", "value": report.get("course_code", "")},
            {"column": "c-nXrSiX6Q7R", "value": report.get("course_name", "")},
            {"column": "c-scopeNotes",  "value": course_level.get("scope_notes", "")},
            {"column": "c-modality",    "value": course_level.get("modality", "")},
            {"column": "c-asmtRat",     "value": course_level.get("assessment_rationale", "")},
            {"column": "c-evidence",    "value": course_level.get("evidence", "")},
            {"column": "c-lrStrategy",  "value": course_level.get("lr_strategy", "")},
            {"column": "c-toolsTech",   "value": course_level.get("tools_tech", "")},
            {"column": "c-asmtNotes",   "value": course_level.get("asmt_notes", "")},
        ] + metadata_cells

        # Determine action from approved diffs
        course_diff = next((d for d in req.diffs if d["table"] == "_Courses"), None)
        if course_diff and course_diff["action"] == "update" and course_row_id:
            await update_row(client, doc_id, "grid-8i2Q6-eoTP", course_row_id, course_cells, headers)
            log.append(f"✓ Step 1-2: Updated _Courses row {course_row_id}")
        else:
            result = await upsert_row(client, doc_id, "grid-8i2Q6-eoTP", course_cells, headers)
            new_ids = [r["id"] for r in result.get("addedRowIds", [])]
            course_row_id = new_ids[0] if new_ids else course_row_id
            log.append(f"✓ Step 1-2: Created _Courses row {course_row_id}")
        written += 1

        # ── Step 3: _Progs | _Courses ────────────────────────────────────────
        prog_course_diff = next((d for d in req.diffs if d["table"] == "_Progs | _Courses"), None)
        if prog_course_diff and prog_course_diff["action"] == "new":
            pc_cells = [
                {"column": "c-UaE_k1Ivfh", "value": course_row_id},
                {"column": "c-aGpuFk4ifn", "value": program_row_id},
            ]
            await upsert_row(client, doc_id, "grid-fEebuvIQBl", pc_cells, headers)
            log.append(f"✓ Step 3: Created _Progs|_Courses pairing")
            written += 1
        else:
            log.append(f"  Step 3: _Progs|_Courses pairing already exists — skipped")

        # ── Steps 4-9: Competencies, skills, junctions ───────────────────────
        # NOTE: Full column IDs for _Comps, _RSDs, junction tables
        # will be wired in Phase 3 once confirmed against sandbox.
        # Placeholder logs for now so the commit response is complete.
        comp_row_ids = {}
        for comp in competencies:
            log.append(f"  Step 4-9: Competency {comp.get('order')} '{comp.get('title')}' — Phase 3 (pending column ID confirmation)")

        log.append(f"✓ Commit complete. {written} rows written. Competency/skill writes pending Phase 3.")

    return {
        "success": True,
        "request_id": req.request_id,
        "rows_written": written,
        "log": log,
    }
